### ISSUE TITLE
export 'ChessBoard' was not found in 'chessboardjs-vue' (on Nuxt)

### ISSUE THREAD

**Issue by scalemaildev** [technoo0/chessboardjs-vue#3]
I see there's a TODO in index.js to add the module exports. Any chance of adding this?

**Comment by technoo0** [comment]
I already exported the module in line 665
https://github.com/technoo0/chessboardjs-vue/blob/7e72eb8f53e7ce53162f59b75abed8010be8601d/index.js#L665
