### ISSUE TITLE
Highligth squares

### ISSUE THREAD

**Issue by rodolphonetto** [technoo0/chessboardjs-vue#4]
Is there a way to implement this exemple? I got a kind confused since it is not jquery here

https://chessboardjs.com/examples#5004

**Comment by Shivakumar-ZugZwang** [comment]
did you Integrated chess.js?

**Comment by rodolphonetto** [comment]
> did you Integrated chess.js?

Yes I did. I have the squares I want to highlight I just dont know how to change the css it self since I dont use jquery as this exempl

**Comment by Shivakumar-ZugZwang** [comment]
Can you help me out to integrate chess.js in vue?

**Comment by rodolphonetto** [comment]
> Can you help me out to integrate chess.js in vue?

I would but my integration is simple, I only send the fen from chess.js to the board, I dont use drag and drop, they are not "integrated" I just send a new fen to the board when my chess.js receives a move from other source.

**Comment by technoo0** [comment]
I think you can do the highlight like this and the rest of the steps as the example 

```
import ChessBoard from "chessboardjs-vue";
    
board =  ChessBoard('board1',"start");
board .highlight(squarepos) // ex :   board .highlight("e2") 
board .removeHightlight(squarepos)

```

**Comment by rodolphonetto** [comment]
> I think you can do the highlight like this and the rest of the steps as the example
> 
> ```
> import ChessBoard from "chessboardjs-vue";
>     
> board =  ChessBoard('board1',"start");
> board .highlight(squarepos) // ex :   board .highlight("e2") 
> board .removeHightlight(squarepos)
> ```

Worked as easy as you said, thank you so much!
